FROM nginx:alpine

LABEL maintainer="YanlongMa <json_vip@163.com>"

VOLUME /var/www
WORKDIR /var/www

EXPOSE 80 443

#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

